const express = require("express"), app = express()
const bodyParser = require("body-parser")
const cors = require('cors')
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.use(cors())
let index = require("./routes/index")
let users = require("./routes/users")
let login = require("./routes/login")
let questions = require("./routes/questions")
let answers = require("./routes/answers")
app.use('/', index)
app.use('/login', login)
app.use('/users', users)
app.use('/questions', questions)
app.use('/answers', answers)
app.listen(5005, () => {
    console.log("Ready on PORT 5005")
})